# Generated by Django 5.2.6 on 2026-09-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_domain_model_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['status', 'due_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='futureplan',
            options={'ordering': ['status', 'target_date', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='action',
            new_name='crm_action_opportu_c6f0fa_idx',
            old_name='crm_action_opportu_56b1ef_idx',
        ),
        migrations.RenameIndex(
            model_name='action',
            new_name='crm_action_status_16c925_idx',
            old_name='crm_action_status_1bc13a_idx',
        ),
        migrations.RenameIndex(
            model_name='assessment',
            new_name='crm_assessm_opportu_a2ff9b_idx',
            old_name='crm_assess_opportu_0c4e8f_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='crm_company_name_895a0e_idx',
            old_name='crm_company_name_7c7c9e_idx',
        ),
        migrations.RenameIndex(
            model_name='company',
            new_name='crm_company_lifecyc_4c6ec8_idx',
            old_name='crm_company_lifecyc_03c56b_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='crm_contact_company_5c18c4_idx',
            old_name='crm_contact_company_6c2f74_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='crm_contact_email_240305_idx',
            old_name='crm_contact_email_5e7f36_idx',
        ),
        migrations.RenameIndex(
            model_name='futureplan',
            new_name='crm_futurep_opportu_aa27af_idx',
            old_name='crm_futurepl_opportu_4baf63_idx',
        ),
        migrations.RenameIndex(
            model_name='futureplan',
            new_name='crm_futurep_target__6df3dc_idx',
            old_name='crm_futurepl_target_8c2df1_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='crm_interac_company_6cb68d_idx',
            old_name='crm_interac_company_3ee0e3_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='crm_interac_opportu_e18a41_idx',
            old_name='crm_interac_opportu_530bab_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='crm_opportu_company_40bb6a_idx',
            old_name='crm_opport_company_8e0e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='crm_opportu_status_307a33_idx',
            old_name='crm_opport_status_5f4e5b_idx',
        ),
        migrations.RenameIndex(
            model_name='opportunity',
            new_name='crm_opportu_expecte_3af026_idx',
            old_name='crm_opport_expecte_8d5e76_idx',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='action',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='crm.opportunity'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='crm.opportunity'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='opportunity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.opportunity'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
